### PR TITLE
Remove redundant call to addService after modifiedService is called.

### PR DESCRIPTION
**Pull request by taestell**
This fixes the Jira Issue: https://issues.apache.org/jira/browse/SLING-7731

### CODE REVIEW

**Comment by rombert** [comment]
@cziegeler  - I think you are the original author of the code, can you please review?

**Comment by rombert** [comment]
@taestell - can you please:

- squash the two commits into a single one
- reference the Jira issue in the title ( e.g. SLING-7731 - Call to addService is no longer needed for modification events in SlingAuthenticatorServiceListener )
- drop the whitespace change or make it a separate commit (in this case it's ok to have two commits - one for the actual fix, one for the whitespace change )

and then force-push the branch?

Thanks!

**Comment by taestell** [comment]
@rombert - Okay, I think it should be ready to merge now. Let me know if any other changes are needed.

**Comment by rombert** [comment]
Merged, thanks a lot for the contribution @taestell !

**Pull request merged**
